from pathlib import Path

p=Path('assets/dungeon/dungeon-zone-content-167824.js')
s=p.read_text(encoding='utf-8')
old='function inventoryState(hero){try{if(typeof ROOT.loadState==="function")return ROOT.loadState(hero)}catch(e){}return null}\nfunction saveInventoryState(hero,st){if(!st)return false;try{if(typeof ROOT.key==="function"){localStorage.setItem(ROOT.key(hero),JSON.stringify(st));return true}}catch(e){}try{ROOT.saveState?.(hero,st);return true}catch(e){}return false}\nfunction addInventoryItem(hero,itemId,qty){const st=inventoryState(hero);if(!st)return false;st.inventory=Array.isArray(st.inventory)?st.inventory:[];for(let i=0;i<qty;i++){let entry={itemId};try{if(typeof ROOT.makeInventoryEntry==="function")entry=ROOT.makeInventoryEntry(itemId)}catch(e){}st.inventory.push(entry)}return saveInventoryState(hero,st)}\nfunction addGold(hero,amount){const st=inventoryState(hero);if(!st)return false;let current=Number(st.gold)||0;try{if(typeof ROOT.gensHeroGold==="function")current=Number(ROOT.gensHeroGold(hero))||0}catch(e){}st.gold=current+Math.max(0,Number(amount)||0);return saveInventoryState(hero,st)}\nfunction grantRewards(hero,gold,items){if(gold>0)addGold(hero,gold);for(const it of normalizeItems(items))addInventoryItem(hero,it.itemId,it.qty)}'
new='function heroStorageKey(hero){try{if(typeof ROOT.key==="function")return String(ROOT.key(hero))}catch(e){}return "z40k_"+String(hero||"")+"_v1"}\nfunction inventoryState(hero){try{if(typeof ROOT.loadState==="function"){const st=ROOT.loadState(hero);if(st&&typeof st==="object")return st}}catch(e){}const st=readJson(heroStorageKey(hero),null);return st&&typeof st==="object"?st:null}\nfunction saveInventoryState(hero,st){if(!st)return false;try{localStorage.setItem(heroStorageKey(hero),JSON.stringify(st));return true}catch(e){return false}}\nfunction rewardInventoryEntry(itemId){try{if(typeof ROOT.makeInventoryEntry==="function")return ROOT.makeInventoryEntry(itemId)}catch(e){}let it=null;try{it=(ROOT.dungeonItems?.()||[]).find(x=>String(x?.id||"")===String(itemId))||null}catch(e){}return {uid:"i_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,8),itemId:String(itemId),ammo:Math.max(0,Number(it?.ammoCapacity)||0),reloads:Math.max(0,Number(it?.reloads)||0)}}\nfunction addInventoryItem(hero,itemId,qty){const st=inventoryState(hero);if(!st)return false;st.inventory=Array.isArray(st.inventory)?st.inventory:[];for(let i=0;i<qty;i++)st.inventory.push(rewardInventoryEntry(itemId));return saveInventoryState(hero,st)}\nfunction addGold(hero,amount){const st=inventoryState(hero);if(!st)return false;let current=Number(st.gold)||0;try{if(typeof ROOT.gensHeroGold==="function")current=Number(ROOT.gensHeroGold(hero))||current}catch(e){}st.gold=current+Math.max(0,Number(amount)||0);return saveInventoryState(hero,st)}\nfunction grantRewards(hero,gold,items){const st=inventoryState(hero);if(!st)return false;st.inventory=Array.isArray(st.inventory)?st.inventory:[];let current=Number(st.gold)||0;try{if(typeof ROOT.gensHeroGold==="function")current=Number(ROOT.gensHeroGold(hero))||current}catch(e){}st.gold=current+Math.max(0,Number(gold)||0);for(const it of normalizeItems(items))for(let i=0;i<it.qty;i++)st.inventory.push(rewardInventoryEntry(it.itemId));const ok=saveInventoryState(hero,st);if(ok)try{ROOT.renderInventory?.();ROOT.renderHands?.();ROOT.renderGear?.()}catch(e){}return ok}'
if old not in s: raise SystemExit('inventory reward block not found')
s=s.replace(old,new,1)
old='function openChest(chestId){const ctx=currentContext();if(!ctx||!ctx.hero)return false;const chest=ctx.content.chests.find(c=>c.id===String(chestId));if(!chest||ctx.state.openedChests[chest.id])return false;grantRewards(ctx.hero,chest.gold,chest.items);ctx.state.openedChests[chest.id]=true;markCellFloor(ctx.x,chest.cell);removeExactChestScene(chest.id);persistSpatial(ctx.x);writeRuntime(ctx.x);try{ROOT.showToast?.("🎁 Coffre ouvert · "+chest.gold+" or · "+chest.items.reduce((n,i)=>n+i.qty,0)+" objet(s)")}catch(e){}try{ROOT.DungeonCore01?.render?.()}catch(e){}return true}'
new='function openChest(chestId){const ctx=currentContext();if(!ctx||!ctx.hero)return false;const chest=ctx.content.chests.find(c=>c.id===String(chestId));if(!chest||ctx.state.openedChests[chest.id])return false;const itemCount=chest.items.reduce((n,i)=>n+i.qty,0);if(!grantRewards(ctx.hero,chest.gold,chest.items)){try{ROOT.DungeonCore01?.modal?.("⚠️ Coffre non ouvert","La récompense n’a pas pu être enregistrée dans l’inventaire. Le coffre reste disponible.")}catch(e){}return false}ctx.state.openedChests[chest.id]=true;markCellFloor(ctx.x,chest.cell);removeExactChestScene(chest.id);persistSpatial(ctx.x);writeRuntime(ctx.x);try{ROOT.showToast?.("🎁 Coffre ouvert · "+chest.gold+" or · "+itemCount+" objet(s)")}catch(e){}try{ROOT.DungeonCore01?.modal?.("🎁 Coffre ouvert",(chest.gold?chest.gold+" or":"")+(chest.gold&&itemCount?" · ":"")+(itemCount?itemCount+" objet(s) ajouté(s) à l’inventaire":""));ROOT.DungeonCore01?.render?.()}catch(e){}return true}'
if old not in s: raise SystemExit('openChest block not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

p=Path('tests/dungeon_zone_content_v167824.test.cjs')
t=p.read_text(encoding='utf-8')
needle="assert.deepEqual(JSON.parse(JSON.stringify(api.parseRewardItems('potion_heal*2, sword_01 x 3'))),[{itemId:'potion_heal',qty:2},{itemId:'sword_01',qty:3}]);\n"
extra="// Browser-realistic regression: exact chest rewards must still work when loadState/key/makeInventoryEntry are not exposed on window.\ndelete context.loadState;delete context.key;delete context.makeInventoryEntry;delete context.gensHeroGold;\nstore.setItem('z40k_aldren_v1',JSON.stringify({inventory:[],gold:7,wounds:0}));\nx=JSON.parse(store.getItem(RT));x.last.worldContentApplied167824=null;x.positions.aldren=4;store.setItem(RT,JSON.stringify(x));\napi.saveZoneContent('d1','n1',{mode:'fixed',chests:[{id:'browserChest',cell:4,rarity:'legendary',gold:3,items:[{itemId:'ditem_ash_blade',qty:1}]}]});\nassert.equal(api.applyCurrentZone({force:true}),true);\nassert.equal(api.openChest('browserChest'),true,'exact chest must write rewards through the real hero storage even without legacy globals');\nconst browserHero=JSON.parse(store.getItem('z40k_aldren_v1'));assert.equal(browserHero.gold,10);assert.equal(browserHero.inventory.filter(i=>i.itemId==='ditem_ash_blade').length,1);\n\n"+needle
if needle not in t: raise SystemExit('test insertion marker missing')
t=t.replace(needle,extra,1)
p.write_text(t,encoding='utf-8')
