from pathlib import Path

p=Path('assets/dungeon/dungeon-zone-content-167824.js')
s=p.read_text(encoding='utf-8')
old='function persistSpatial(x){try{ROOT.DungeonSpatial313?.ensure?.(x);ROOT.DungeonSpatial313?.persist?.(x)}catch(e){}}\nfunction applyCurrentZone(options){const opts=options||{},ctx=currentContext();if(!ctx||ctx.content.mode==="inherit")return false;const {x,dungeonId,nodeId,content}=ctx;if(x.last?.worldContentApplied167824&&!opts.force)return false;const room=Number(x.room)||0;if(content.mode==="fixed")removeRoomEnemies(room);syncMapMarkers(x,content);x.enemyCells=x.enemyCells&&typeof x.enemyCells==="object"?x.enemyCells:{};if(content.mode==="fixed")x.enemyCells={};let keyId="";for(const spec of content.enemies){const cell=clampCell(dungeonId,nodeId,spec.cell),ids=spawnEnemy(spec.enemyId,spec.qty,room,cell,spec.hp);for(const id of ids)x.enemyCells[id]=cell;if(spec.hasKey&&ids[0])keyId=ids[0]}if(keyId)x.last.keyEnemyId=keyId;if(content.mode==="fixed"&&!content.enemies.length){x.last.exitLocked=false;x.last.keyEnemyId=""}x.last.worldContentApplied167824={version:APPLIED_VERSION,dungeonId,nodeId,updatedAt:content.updatedAt||"",mode:content.mode};x.last.worldZoneContent167824=clone(content);stateFor(x,dungeonId,nodeId);persistSpatial(x);writeRuntime(x);return true}'
new='function persistSpatial(x){try{ROOT.DungeonSpatial313?.ensure?.(x);ROOT.DungeonSpatial313?.persist?.(x)}catch(e){}}\nfunction chestSceneElements(){try{return ROOT.loadDungeonSceneElements?.()||[]}catch(e){return []}}\nfunction syncExactChestScenes(x,dungeonId,nodeId,content){if(!content?.chests?.length)return 0;const room=Number(x?.room)||0,all=chestSceneElements();let changed=false,count=0;for(const c of content.chests){const cell=clampCell(dungeonId,nodeId,c.cell);let el=all.find(e=>e?.kind==="chest"&&Number(e?.room||0)===room&&Number(e?.cellIndex)===cell);if(!el){try{el=ROOT.addDungeonSceneElement?.({kind:"chest",name:"Coffre "+String(c.rarity||"common"),rarity:String(c.rarity||"common"),trapped:false,room,cellIndex:cell,fromMap:true})||null}catch(e){}}if(el){el.cellIndex=cell;el.rarity=String(c.rarity||"common");el.name="Coffre "+String(c.rarity||"common");el.trapped=false;el.exactChest167824=true;el.exactChestId167824=String(c.id);el.exactDungeonId167824=String(dungeonId);el.exactNodeId167824=String(nodeId);el.challenge=null;el.challengeDone=true;changed=true;count++}}if(changed)try{ROOT.saveDungeonSceneElements?.(all)}catch(e){}return count}\nfunction removeExactChestScene(chestId){const id=String(chestId||""),all=chestSceneElements(),el=all.find(e=>e?.kind==="chest"&&String(e?.exactChestId167824||"")===id);if(!el)return false;try{ROOT.removeDungeonSceneElement?.(String(el.id));return true}catch(e){}try{ROOT.saveDungeonSceneElements?.(all.filter(e=>e!==el));return true}catch(e){}return false}\nfunction exactChestForSceneId(sceneId){const id=String(sceneId||""),el=chestSceneElements().find(e=>String(e?.id)===id&&e?.kind==="chest"&&e?.exactChest167824);if(!el)return null;const ctx=currentContext();if(!ctx)return null;const chest=ctx.content.chests.find(c=>String(c.id)===String(el.exactChestId167824));return chest?{el,chest,ctx}:null}\nfunction applyCurrentZone(options){const opts=options||{},ctx=currentContext();if(!ctx||ctx.content.mode==="inherit")return false;const {x,dungeonId,nodeId,content}=ctx;if(x.last?.worldContentApplied167824&&!opts.force)return false;const room=Number(x.room)||0;if(content.mode==="fixed")removeRoomEnemies(room);syncMapMarkers(x,content);syncExactChestScenes(x,dungeonId,nodeId,content);x.enemyCells=x.enemyCells&&typeof x.enemyCells==="object"?x.enemyCells:{};if(content.mode==="fixed")x.enemyCells={};let keyId="";for(const spec of content.enemies){const cell=clampCell(dungeonId,nodeId,spec.cell),ids=spawnEnemy(spec.enemyId,spec.qty,room,cell,spec.hp);for(const id of ids)x.enemyCells[id]=cell;if(spec.hasKey&&ids[0])keyId=ids[0]}if(keyId)x.last.keyEnemyId=keyId;if(content.mode==="fixed"&&!content.enemies.length){x.last.exitLocked=false;x.last.keyEnemyId=""}x.last.worldContentApplied167824={version:APPLIED_VERSION,dungeonId,nodeId,updatedAt:content.updatedAt||"",mode:content.mode};x.last.worldZoneContent167824=clone(content);stateFor(x,dungeonId,nodeId);persistSpatial(x);writeRuntime(x);return true}'
if old not in s: raise SystemExit('applyCurrentZone marker not found')
s=s.replace(old,new,1)
old='function openChest(chestId){const ctx=currentContext();if(!ctx||!ctx.hero)return false;const chest=ctx.content.chests.find(c=>c.id===String(chestId));if(!chest||ctx.state.openedChests[chest.id])return false;grantRewards(ctx.hero,chest.gold,chest.items);ctx.state.openedChests[chest.id]=true;markCellFloor(ctx.x,chest.cell);persistSpatial(ctx.x);writeRuntime(ctx.x);try{ROOT.showToast?.("🎁 Coffre ouvert · "+chest.gold+" or · "+chest.items.reduce((n,i)=>n+i.qty,0)+" objet(s)")}catch(e){}try{ROOT.DungeonCore01?.render?.()}catch(e){}return true}'
new='function openChest(chestId){const ctx=currentContext();if(!ctx||!ctx.hero)return false;const chest=ctx.content.chests.find(c=>c.id===String(chestId));if(!chest||ctx.state.openedChests[chest.id])return false;grantRewards(ctx.hero,chest.gold,chest.items);ctx.state.openedChests[chest.id]=true;markCellFloor(ctx.x,chest.cell);removeExactChestScene(chest.id);persistSpatial(ctx.x);writeRuntime(ctx.x);try{ROOT.showToast?.("🎁 Coffre ouvert · "+chest.gold+" or · "+chest.items.reduce((n,i)=>n+i.qty,0)+" objet(s)")}catch(e){}try{ROOT.DungeonCore01?.render?.()}catch(e){}return true}'
if old not in s: raise SystemExit('openChest marker not found')
s=s.replace(old,new,1)
old='function wrapCore(){const core=ROOT.DungeonCore01;if(!core)return false;if(typeof core.explore==="function"&&!core.explore.__dzc167824){'
new='function wrapCore(){const core=ROOT.DungeonCore01;if(!core)return false;if(typeof core.searchChest==="function"&&!core.searchChest.__dzcExactChest167824){const oldC=core.searchChest.bind(core),cw=function(id){const exact=exactChestForSceneId(id);if(!exact)return oldC(id);const pos=Number(exact.ctx.x.positions?.[exact.ctx.hero]),cell=Number(exact.chest.cell);if(Number.isFinite(pos)&&pos!==cell){try{core.modal?.("🎁 Coffre","📍 Place le héros actif exactement sur la case du coffre.")}catch(e){}return false}return openChest(exact.chest.id)};cw.__dzcExactChest167824=true;cw.__dzcExactChestOriginal=oldC;core.searchChest=cw}if(typeof core.explore==="function"&&!core.explore.__dzc167824){'
if old not in s: raise SystemExit('wrapCore marker not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

p=Path('tests/dungeon_zone_content_v167824.test.cjs')
t=p.read_text(encoding='utf-8')
# Extend context with scene functions before VM evaluation.
old='let seq=0;\nconst heroState={inventory:[],gold:5,wounds:0};'
new='let seq=0;\nlet scenes=[];let sceneSeq=0;\ncontextScenesPlaceholder=None\nconst heroState={inventory:[],gold:5,wounds:0};'
# avoid awkward forward ref: use a direct insertion in context definition instead
if 'contextScenesPlaceholder=None' in t: raise SystemExit('unexpected placeholder')
oldctx=' loadActiveEnemies(){return enemies},saveActiveEnemies(v){enemies=v},\n trackSpawnedEnemyInstances'
newctx=' loadActiveEnemies(){return enemies},saveActiveEnemies(v){enemies=v},\n loadDungeonSceneElements(){return scenes},saveDungeonSceneElements(v){scenes=v},addDungeonSceneElement(v){const el={id:"scene-"+(++sceneSeq),...v};scenes.push(el);return el},removeDungeonSceneElement(id){scenes=scenes.filter(e=>String(e.id)!==String(id));return true},\n trackSpawnedEnemyInstances'
if oldctx not in t: raise SystemExit('context scene marker not found')
t=t.replace('let seq=0;\nconst heroState={inventory:[],gold:5,wounds:0};','let seq=0;\nlet scenes=[],sceneSeq=0;\nconst heroState={inventory:[],gold:5,wounds:0};',1)
t=t.replace(oldctx,newctx,1)
marker="assert.equal(api.applyCurrentZone(),true);\nlet x=JSON.parse(store.getItem(RT));\n"
extra="assert.equal(api.applyCurrentZone(),true);\nassert.equal(scenes.length,1,'exact authored chest must have one linked scene element');assert.equal(scenes[0].rarity,'rare','scene chest must use authored rarity instead of a random rarity');assert.equal(scenes[0].exactChest167824,true);assert.equal(scenes[0].exactChestId167824,'ch1');\nlet x=JSON.parse(store.getItem(RT));\n"
if marker not in t: raise SystemExit('apply test marker not found')
t=t.replace(marker,extra,1)
marker="assert.equal(api.openChest('ch1'),true,'exact chest must open once');\n"
extra="assert.equal(api.openChest('ch1'),true,'exact chest must open once');assert.equal(scenes.length,0,'opening an exact chest must remove its linked legacy scene element');\n"
t=t.replace(marker,extra,1)
p.write_text(t,encoding='utf-8')
