const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const src=fs.readFileSync(path.join(root,'assets','dungeon','dungeon-grid-flicker-guard-167876.js'),'utf8');
assert.doesNotThrow(()=>new Function(src),'source render stability module must stay syntactically valid');
assert.match(src,/APP_VERSION="16\.78\.77"/);
assert.match(src,/function patchMapHtml/,'terrain must be patched before live DOM insertion');
assert.match(src,/tpl\.innerHTML=html/,'source renderer must decorate detached map HTML');
assert.match(src,/dng_floor_"\+t\+"_"\+v\+"\.png/,'authored biome floors must be applied at source');
assert.match(src,/dng_wall_block\.jpg/,'validated wall asset must be applied at source');
assert.match(src,/function paintTokensNow/,'Core 3.10 tokens must be restored synchronously');
assert.match(src,/\.dc310Hero,\.dc310Enemy/,'hero and enemy tokens must share immediate rendering');
assert.match(src,/__dac167852TokenObserver/,'late scale observer must be disabled');
assert.match(src,/\.disconnect\(\)/,'late observer must actually be disconnected');
assert.match(src,/@container \(max-width:82px\)/,'medium map token scaling must stay responsive in CSS');
assert.match(src,/@container \(max-width:54px\)/,'large map compact token scaling must stay responsive in CSS');
assert.doesNotMatch(src,/cloneNode\(true\)|position:fixed!important/,'obsolete snapshot overlay must be removed');
assert.doesNotMatch(src,/positions\s*=|enemyCells\s*=|localStorage\.setItem|saveDungeon|saveActiveEnemies/,'visual stability fix must not mutate gameplay state');
const siteIndex=process.argv[2]&&fs.existsSync(process.argv[2])?fs.readFileSync(process.argv[2],'utf8'):null;
if(siteIndex)assert.match(siteIndex,/dungeon-grid-flicker-guard-167876\.js\?v=167876/,'deployed index must load source render stability module');
console.log('Dungeon source-time terrain/token stability V16.78.77 regression: OK');
