const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const bootSrc=fs.readFileSync(path.join(root,'assets','dungeon','dungeon-authored-bootstrap-167849.js'),'utf8');
const guardSrc=fs.readFileSync(path.join(root,'assets','dungeon','dungeon-authored-cache-guard-167849.js'),'utf8');
const feedback=fs.readFileSync(path.join(root,'assets','dungeon','dungeon-room-creator-feedback-167821.js'),'utf8');
const RT='gensrpg_dungeon_runtime_v2',PRIMARY='gensrpg_dungeon_primary_selection_v167833';
const store=new Map([[PRIMARY,JSON.stringify({kind:'world',id:'world-1'})],[RT,JSON.stringify({room:1,last:{authoredRuntime167839:true,worldDungeonId:'world-1',worldNodeId:'A',map:{cells:['entry','floor','cache','floor','exit']}}})]]);
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v))};
let capture=null,travelCalls=0,legacyCalls=0,syncCalls=0,loaded=[];
const explore={id:'dc01Explore',closest(sel){return sel==='#dc01Explore'?this:null}};
const document={readyState:'complete',body:{appendChild(s){loaded.push(s.src);if(s.src.includes('zone-links'))context.DungeonZoneLinks167846={install(){}};if(s.src.includes('cache-guard')){vm.runInContext(guardSrc,context);s.listeners?.load?.()}return s}},createElement(){return {dataset:{},listeners:{},addEventListener(n,fn){this.listeners[n]=fn}}},querySelector(){return null},addEventListener(n,fn,opt){if(n==='click'&&opt===true&&!capture)capture=fn},getElementById(id){return id==='dc01Explore'?explore:null}};
const context={console,JSON,Math,Date,localStorage,document,setTimeout(fn){fn();return 1},showToast(){},DungeonAuthoredRuntime167839:{active(){return true},install(){return true},syncActionButton(){syncCalls++;return true},travel(){travelCalls++;return true}},DungeonCore01:{explore(){legacyCalls++}}};context.window=context;context.globalThis=context;vm.createContext(context);
vm.runInContext(bootSrc,context,{filename:'dungeon-authored-bootstrap-167849.js'});
assert.ok(context.DungeonAuthoredBootstrap167849);assert.ok(capture,'capture-phase guard must be installed');
const evt={target:explore,preventDefault(){this.prevented=true},stopImmediatePropagation(){this.stopped=true}};capture(evt);assert.equal(travelCalls,1,'stale visible Explore must route directly to authored travel');assert.equal(legacyCalls,0,'legacy random explore must never run for a selected built world');assert.equal(evt.prevented,true);assert.equal(evt.stopped,true);assert.ok(syncCalls>=1);
assert.ok(loaded.some(x=>x.includes('dungeon-zone-links-167846.js')),'production bootstrap must load zone links');assert.ok(loaded.some(x=>x.includes('dungeon-authored-cache-guard-167849.js')),'production bootstrap must load cache guard');
const guard=context.DungeonAuthoredCacheGuard167849;assert.ok(guard);const rt=JSON.parse(localStorage.getItem(RT));guard.sanitize(rt);assert.deepEqual(rt.last.map.cells,['entry','floor','floor','floor','exit'],'authored cache marker must be invisible to legacy semantic handlers');assert.deepEqual(rt.last.authoredCacheCells167849,[2],'cache position must remain recorded for authored interactions');
assert.match(feedback,/dungeon-authored-bootstrap-167849\.js\?v=167849/,'a module already shipped by Pages must load the bootstrap');
console.log('Authored first-click/cache production bootstrap V16.78.49: OK');
