const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const root=path.join(__dirname,'..'),src=fs.readFileSync(path.join(root,'assets','dungeon','dungeon-zone-content-167824.js'),'utf8');
const RT='gensrpg_dungeon_runtime_v2',CONTENT='gensrpg_zone_instance_content_v1';
function storage(initial={}){const m=new Map(Object.entries(initial));return {getItem(k){return m.has(k)?m.get(k):null},setItem(k,v){m.set(k,String(v))},removeItem(k){m.delete(k)}}}
const clone=v=>JSON.parse(JSON.stringify(v));function node(text=''){return {id:'',textContent:text,innerHTML:'',style:{},classList:{add(){},remove(){}},parentNode:null,remove(){this.removed=true},appendChild(){},insertBefore(){},addEventListener(){},setAttribute(){}}}
const cards=[node('Coffre Rare'),node('Coffre Commun'),node('Coffre Épique')],document={readyState:'complete',head:{appendChild(){}},body:{appendChild(){}},documentElement:{},createElement(){return node()},getElementById(){return null},querySelector(){return null},querySelectorAll(sel){return sel==='#dc200Scene .dc200SceneCard'?cards:[]},addEventListener(){}};
const map={size:3,width:3,height:3,cells:['entry','floor','floor','enemy','floor','chest','trap','floor','exit'],entryIdx:0,exitIdx:8};
const runtime={participants:['hero'],index:0,room:1,positions:{hero:0},remaining:{hero:3},enemyCells:{},roomStates:{},last:{authoredRuntime167839:true,worldRuntime167823:true,worldDungeonId:'d1',worldNodeId:'n1',worldContentApplied167824:{version:1,mode:'fixed'},map:clone(map)}};
const content={d1:{n1:{mode:'fixed',enemies:[{id:'enemy-spec',enemyId:'dng_skeleton',qty:1,cell:3,role:'enemy'}],chests:[{id:'exact-chest',cell:5,rarity:'rare',gold:7,items:[{itemId:'potion_heal',qty:1}]}],traps:[{id:'exact-trap',cell:6,trapType:'reference',refId:'dtrap_rune',once:true}],puzzles:[],npcs:[],items:[]}}};
const store=storage({[RT]:JSON.stringify(runtime),[CONTENT]:JSON.stringify(content)});let enemies=[],spawnCount=0,trapOpened='',enemiesSeenByBaseRender=0;
const legacyScenes=[{id:'old1',kind:'chest',room:1},{id:'old2',kind:'chest',room:1},{id:'secret',kind:'chest',room:1,branch200:true},{id:'merchant',kind:'merchant',room:1}];
const core={render(){enemiesSeenByBaseRender=enemies.filter(e=>e.hp>0&&e.dungeonRoom===1).length;return true},show(){return this.render()},explore(){return true}};
const context={console,Math,Date,document,localStorage:store,setTimeout(){return 1},DungeonCore01:core,loadDungeonSceneElements(){return clone(legacyScenes)},DungeonWorldBuilder167821:{findDungeon(){return {nodes:[{id:'n1',roomId:'room1'}]}},loadLibrary(){return []}},DungeonRoomCreator100:{findRoom(){return {id:'room1',width:3,height:3,cells:Array(9).fill({terrain:'floor'})}}},DungeonWorldRuntime167823:{},DungeonSpatial313:{ensure(x){return x},persist(x){return x}},loadActiveEnemies(){return enemies},saveActiveEnemies(v){enemies=v},trackSpawnedEnemyInstances(type,qty,room){const ids=[];for(let i=0;i<qty;i++){const id='spawn-'+(++spawnCount);ids.push(id);enemies.push({id,enemyId:type,hp:5,maxHp:5,dungeonRoom:Number(room)||1})}return ids},loadState(){return {inventory:[],gold:0,wounds:0}},key(){return 'hero-state'},makeInventoryEntry(id){return {itemId:id}},gensHeroGold(){return 0},openDungeonTrap(id){trapOpened=id;return true},showToast(){},modal(){}};
context.window=context;context.globalThis=context;vm.createContext(context);vm.runInContext(src,context);
const api=context.DungeonZoneContent167824;assert.equal(api.APP_VERSION,'16.78.45');assert.deepEqual(context.loadDungeonSceneElements().map(x=>x.id),['secret','merchant']);
core.render();let x=JSON.parse(store.getItem(RT));assert.equal(spawnCount,1);assert.equal(enemiesSeenByBaseRender,1);assert.equal(enemies[0].hp,5);assert.equal(x.enemyCells[enemies[0].id],3);assert.equal(x.last.map.cells[3],'enemy');assert.equal(x.last.map.cells[6],'floor');assert.equal(x.last.worldContentApplied167824.version,2);assert.ok(x.last.worldContentApplied167824.signature);
core.render();assert.equal(spawnCount,1);enemies[0].hp=0;context.saveActiveEnemies(enemies);core.render();assert.equal(spawnCount,1,'un ennemi vaincu ne doit pas respawn');
x=JSON.parse(store.getItem(RT));x.positions.hero=6;store.setItem(RT,JSON.stringify(x));core.render();assert.equal(trapOpened,'dtrap_rune');x=JSON.parse(store.getItem(RT));x.last.authoredRuntime167839=false;store.setItem(RT,JSON.stringify(x));assert.equal(context.loadDungeonSceneElements().filter(e=>e.kind==='chest').length,3);
assert.doesNotMatch(src,/new\s+MutationObserver/);console.log('Dungeon live board V16.78.45: OK');
