const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const src=fs.readFileSync(path.join(root,'assets','dungeon','dungeon-ui-cleanup-167874.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
const siteIndex=process.argv[2]&&fs.existsSync(process.argv[2])?fs.readFileSync(process.argv[2],'utf8'):null;

assert.doesNotThrow(()=>new Function(src),'UI cleanup module must stay syntactically valid');
assert.match(src,/APP_VERSION="16\.78\.74"/);
assert.match(src,/ennemi\\\(s\\\) vivant\\\(s\\\)/i,'living-enemy summary matcher missing');
assert.match(src,/Coffre\\s\+\(\?:commun\|rare\|epic\|épique\|legendary\|légendaire\)/i,'ghost chest matcher missing');
assert.match(src,/!\/Va sur la case\/i\.test\(t\)/,'real chest interaction cards must be preserved');
assert.match(src,/Salle actuelle/i,'cleanup must stop before hiding the room section itself');
assert.match(src,/display:none!important/,'cleanup hidden class missing');
assert.match(src,/DungeonCore01/,'cleanup must attach to Dungeon render lifecycle');
assert.match(src,/\["render","show"\]/,'cleanup must rerun after Dungeon renders');
assert.doesNotMatch(src,/MutationObserver/,'UI cleanup must not add a global DOM observer');
assert.doesNotMatch(src,/localStorage\.setItem|saveDungeon|enemyCells\s*=|positions\s*=|participants\s*=/,'UI cleanup must not mutate gameplay state');
assert.match(sw,/gensrpg-cache-16\.78\.74-ui-cleanup/);
assert.match(sw,/dungeon-ui-cleanup-167874\.js/);
if(siteIndex)assert.match(siteIndex,/dungeon-ui-cleanup-167874\.js\?v=167874/,'deployed index must load UI cleanup module');
console.log('Dungeon UI cleanup V16.78.74 regression: OK');
