const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const src=fs.readFileSync(path.join(__dirname,'..','assets','dungeon','dungeon-authored-cache-ux-167853.js'),'utf8');
const store={gensrpg_dungeon_runtime_v2:JSON.stringify({last:{authoredRuntime167839:true,worldDungeonId:'g',worldNodeId:'A',map:{width:9,height:9,cells:Array(81).fill('floor')}}})};
const timers=[];let paintCalls=0,actionCalls=0;const listeners={};
const styleSnapshot={width:'900px',height:'900px',gridTemplateColumns:'repeat(9,100px)'};
const grid={style:{...styleSnapshot}};
const document={readyState:'complete',addEventListener(t,fn){(listeners[t]||(listeners[t]=[])).push(fn)},querySelector(q){return q==='#dc047RoomBoard .dc047Grid'?grid:null}};
const core={render(){return 'rendered'},show(){return 'shown'}};const originalRender=core.render,originalShow=core.show;
const context={console,JSON,Math,Date,document,localStorage:{getItem(k){return store[k]||null}},setTimeout(fn,ms){timers.push({fn,ms});return timers.length},DungeonZoneLinks167846:{paintTravelButtons(){paintCalls++}},DungeonAuthoredRuntime167839:{syncActionButton(){actionCalls++}},DungeonCore01:core};context.window=context;context.globalThis=context;
vm.createContext(context);vm.runInContext(src,context,{filename:'dungeon-authored-cache-ux-167853.js'});
const api=context.DungeonAuthoredCacheUx167853;assert.ok(api);assert.equal(api.APP_VERSION,'16.78.56');
assert.equal(core.render,originalRender,'cache UX must not wrap Dungeon render');assert.equal(core.show,originalShow,'cache UX must not wrap Dungeon show');
assert.deepEqual(grid.style,styleSnapshot,'cache UX must never change tactical grid geometry');
const cell={closest(sel){return sel==='#dc047RoomBoard .dc047Grid .dc047Cell'?this:null}};for(const fn of listeners.click||[])fn({target:cell});
assert.ok(timers.some(t=>t.ms===0)&&timers.some(t=>t.ms===20)&&timers.some(t=>t.ms===80),'grid click must schedule immediate post-move action refreshes');
while(timers.length)timers.shift().fn();assert.ok(paintCalls>0);assert.ok(actionCalls>0);assert.deepEqual(grid.style,styleSnapshot,'post-move refresh must leave grid geometry untouched');
console.log('Dungeon authored cache UX V16.78.56 no-grid-touch: OK');
