const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const src=fs.readFileSync(path.join(__dirname,'..','assets','dungeon','dungeon-authored-action-fix-167857.js'),'utf8');
const RT='gensrpg_dungeon_runtime_v2';
let rt={room:3,index:0,participants:['lyra'],positions:{lyra:4},last:{authoredRuntime167839:true,worldDungeonId:'world-1',worldNodeId:'A'}};
const store={[RT]:JSON.stringify(rt)};
const listeners={};const timers=[];let paints=0,syncs=0,visuals=0;
function button(text){return {textContent:text,dataset:{},style:{display:''}}}
const legacy=button('🔍 FOUILLER LE COFFRE'),exact=button('🎁 Ouvrir coffre legendary'),other=button('✅ FIN DU TOUR');
const cell={closest(sel){return sel==='#dc047RoomBoard .dc047Grid .dc047Cell'?this:null}};
const document={readyState:'complete',addEventListener(n,fn){(listeners[n]||(listeners[n]=[])).push(fn)},querySelectorAll(sel){return sel==='button'?[legacy,exact,other]:[]}};
const context={console,JSON,Math,Date,document,localStorage:{getItem(k){return store[k]||null}},setTimeout(fn,ms){timers.push({fn,ms});return timers.length},DungeonZoneLinks167846:{paintTravelButtons(){paints++}},DungeonAuthoredRuntime167839:{syncActionButton(){syncs++}},DungeonAuthoredCacheVisual167852:{sync(){visuals++}},DungeonCore01:{render(){},show(){}}};context.window=context;context.globalThis=context;
vm.createContext(context);vm.runInContext(src,context,{filename:'dungeon-authored-action-fix-167857.js'});
const api=context.DungeonAuthoredActionFix167857;assert.ok(api);assert.equal(api.APP_VERSION,'16.78.57');
assert.equal(api.positionKey(JSON.parse(store[RT])),'lyra|3|4');
api.syncActions();assert.equal(legacy.style.display,'none','legacy generic chest button must be hidden in authored worlds');assert.equal(exact.style.display,'','exact legendary button must stay visible');assert.equal(other.style.display,'');assert.ok(paints>0&&syncs>0&&visuals>0);
for(const fn of listeners.pointerdown||[])fn({target:cell});
rt=JSON.parse(store[RT]);rt.positions.lyra=5;store[RT]=JSON.stringify(rt);
for(const fn of listeners.click||[])fn({target:cell});
assert.ok(timers.some(t=>t.ms===25)&&timers.some(t=>t.ms===1100),'mobile movement watch must persist long enough for delayed position updates');
while(timers.length)timers.shift().fn();assert.ok(paints>1,'cache/return actions must repaint after movement');
rt=JSON.parse(store[RT]);delete rt.last.authoredRuntime167839;store[RT]=JSON.stringify(rt);api.syncLegacyChestButton();assert.equal(legacy.style.display,'','legacy button must be restored outside authored runtime');
console.log('Dungeon authored action fix V16.78.57: OK');
