const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'..','assets','dungeon','dungeon-authored-final-exit-167875.js'),'utf8');
assert.doesNotThrow(()=>new Function(src));
assert.match(src,/SORTIE FINALE/);
assert.match(src,/TERMINER LE DONJON/);
assert.doesNotMatch(src,/gens-rpg|stat|talent/i,'final exit module must stay independent from RPG stats');
const store=new Map();
const runtime={room:3,index:0,participants:['dungeon_aldren'],positions:{dungeon_aldren:8},last:{map:{exitIdx:8,cells:['floor','floor','floor','floor','floor','floor','floor','floor','exit'],objective:{status:'open'}},objective:{status:'open'}},branch:{active:false}};
store.set('gensrpg_dungeon_runtime_v2',JSON.stringify(runtime));
const button={textContent:'',disabled:false,onclick:null};
const core={explore(){return 'legacy'},render(){return true},show(){return true},modal(){return true}};
let home=false,session=true;
const ctx={console,setTimeout:f=>f(),clearTimeout,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v))},DungeonCore01:core,DungeonAuthoredRuntime167839:{active:()=>true,graph:()=>({id:'world1'}),plan:()=>({currentNodeId:'node3',outgoing:[],targetNodeId:'',needsExit:false}),positional:()=>true},markSessionActive:v=>{session=!!v},dc033ForceHome:()=>{home=true},saveDungeonState:()=>{},showToast:()=>{}};
ctx.window=ctx;ctx.globalThis=ctx;
vm.createContext(ctx);vm.runInContext(src,ctx,{filename:'dungeon-authored-final-exit-167875.js'});
const api=ctx.DungeonAuthoredFinalExit167875;assert.ok(api);
const f=api.finalState();assert.ok(f&&f.atExit,'terminal authored node on exit cell must be recognized');
assert.equal(api.finish(),true);
const saved=JSON.parse(store.get('gensrpg_dungeon_runtime_v2'));
assert.ok(saved.authoredCompleted167875,'completion marker missing');
assert.equal(saved.last.map.objective.status,'complete');
assert.equal(session,false,'completed Dungeon must not stay resumable as an active session');
assert.equal(home,true,'completed Dungeon must return home');
const runtime2={...runtime,positions:{dungeon_aldren:7},last:{map:{exitIdx:8,cells:runtime.last.map.cells,objective:{status:'open'}},objective:{status:'open'}},branch:{active:false}};
store.set('gensrpg_dungeon_runtime_v2',JSON.stringify(runtime2));home=false;session=true;
assert.equal(api.finish(),false,'tactical hero not on final exit must not finish Dungeon');
assert.equal(home,false);
console.log('Dungeon authored final exit V16.78.75: OK');
