const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const src=fs.readFileSync(path.join(__dirname,'..','assets','dungeon','dungeon-authored-cache-ux-167853.js'),'utf8');
const store={gensrpg_dungeon_runtime_v2:JSON.stringify({last:{authoredRuntime167839:true,worldDungeonId:'g',worldNodeId:'branch_A_2_attic',map:{width:3,height:2,cells:Array(6).fill('floor')}}})};
const timers=[];let paintCalls=0,actionCalls=0;
const style={props:{},set width(v){this.props.width=v},get width(){return this.props.width},set maxWidth(v){this.props.maxWidth=v},set margin(v){this.props.margin=v},set gridTemplateColumns(v){this.props.gridTemplateColumns=v},removeProperty(k){delete this.props[k.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]}};
const boardStyle={props:{},set overflowX(v){this.props.overflowX=v},removeProperty(k){delete this.props[k.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]}};
const grid={style};const board={style:boardStyle};const listeners={};
const document={readyState:'complete',addEventListener(t,fn){(listeners[t]||(listeners[t]=[])).push(fn)},querySelector(q){return q==='#dc047RoomBoard .dc047Grid'?grid:null},getElementById(id){return id==='dc047RoomBoard'?board:null}};
const context={console,JSON,Math,Date,document,localStorage:{getItem(k){return store[k]||null}},setTimeout(fn,ms){timers.push({fn,ms});return timers.length},DungeonZoneLinks167846:{paintTravelButtons(){paintCalls++}},DungeonAuthoredRuntime167839:{syncActionButton(){actionCalls++}},DungeonCore01:{render(){},show(){}}};context.window=context;context.globalThis=context;
vm.createContext(context);vm.runInContext(src,context,{filename:'dungeon-authored-cache-ux-167853.js'});
const api=context.DungeonAuthoredCacheUx167853;assert.ok(api);assert.equal(api.APP_VERSION,'16.78.53');
assert.equal(api.secondaryBranch(JSON.parse(store.gensrpg_dungeon_runtime_v2)),true);
assert.equal(api.fitWidthPx(3),192);assert.equal(api.fitWidthPx(20),560);
assert.equal(api.fitBranchRoom(),true);assert.equal(style.props.width,'min(100%, 192px)');assert.equal(style.props.gridTemplateColumns,'repeat(3, minmax(0,1fr))');assert.equal(boardStyle.props.overflowX,'hidden');
const cell={closest(sel){return sel==='#dc047RoomBoard .dc047Grid .dc047Cell'?this:null}};for(const fn of listeners.click||[])fn({target:cell});
assert.ok(timers.some(t=>t.ms===0)&&timers.some(t=>t.ms===20)&&timers.some(t=>t.ms===80),'grid click must schedule immediate post-move refreshes');
while(timers.length)timers.shift().fn();assert.ok(paintCalls>0,'cache/return buttons must refresh after movement');assert.ok(actionCalls>0,'authored action button must refresh after movement');
store.gensrpg_dungeon_runtime_v2=JSON.stringify({last:{authoredRuntime167839:true,worldDungeonId:'g',worldNodeId:'A',map:{width:9,height:9,cells:Array(81).fill('floor')}}});assert.equal(api.fitBranchRoom(),false,'main authored rooms must not be auto-fitted by this cache UX layer');
console.log('Dungeon authored cache UX V16.78.53: OK');
