const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

const root=path.join(__dirname,'..');
const src=fs.readFileSync(path.join(root,'assets','dungeon','dungeon-event-runtime-fix-167878.js'),'utf8');
const RT='gensrpg_dungeon_runtime_v2';
const store=new Map();
const localStorage={getItem(k){return store.has(k)?store.get(k):null},setItem(k,v){store.set(k,String(v))}};
const runtime={participants:['aldren','lyra'],index:0,room:5,heroRooms:{aldren:5,lyra:5},positions:{aldren:12,lyra:13},enemyCells:{old_enemy:0},last:{map:{size:5,cells:Array(25).fill('floor')}}};
runtime.last.map.cells[0]='enemy';runtime.last.map.cells[24]='exit';
localStorage.setItem(RT,JSON.stringify(runtime));
let enemies=[{id:'old_enemy',enemyId:'dng_skeleton',dungeonRoom:5,hp:3}],renderCalls=0;
const ctx={console,Math,Date,localStorage,setTimeout(fn){fn();return 1},loadActiveEnemies(){return enemies},saveActiveEnemies(v){enemies=v},DungeonSpatial313:{sameView(){return true},persist(){}},DungeonCore01:{render(){renderCalls++;return true}},applyDungeonTurnEvent(evt){if(evt.id==='d_evt_ambush')enemies.push({id:'ambush_new',enemyId:'dng_ghoul',dungeonRoom:5,hp:4});else enemies.push({id:'reinforce_new',enemyId:'dng_ghoul',dungeonRoom:5,hp:4});return {event:evt}}};
ctx.window=ctx;ctx.globalThis=ctx;
vm.createContext(ctx);vm.runInContext(src,ctx,{filename:'dungeon-event-runtime-fix-167878.js'});
const api=ctx.DungeonEventRuntimeFix167878;
assert.ok(api);assert.equal(api.APP_VERSION,'16.78.79');
function dist(cell){const size=5,heroCells=[12,13];return Math.min(...heroCells.map(h=>Math.abs(Math.floor(h/size)-Math.floor(cell/size))+Math.abs((h%size)-(cell%size))))}
ctx.applyDungeonTurnEvent({id:'d_evt_ambush',name:'Embuscade'});
let x=JSON.parse(localStorage.getItem(RT));
const ambush=Number(x.enemyCells.ambush_new);
assert.ok(Number.isInteger(ambush),'le nouvel ennemi d’embuscade doit recevoir une position tactique');
assert.equal(dist(ambush),1,'l’ennemi d’embuscade doit apparaître sur une case adjacente à un héros');
assert.notEqual(ambush,24,'l’embuscade ne doit pas envoyer le monstre au fond sur la sortie');
assert.equal(enemies.find(e=>e.id==='ambush_new').dungeonCell200,ambush);

ctx.applyDungeonTurnEvent({id:'d_evt_reinforce',name:'Renforts ennemis'});
x=JSON.parse(localStorage.getItem(RT));
const reinf=Number(x.enemyCells.reinforce_new);
assert.ok(Number.isInteger(reinf),'un renfort doit lui aussi recevoir une position tactique');
assert.equal(dist(reinf),1,'un renfort doit apparaître près des héros et non au fond de la salle');
assert.notEqual(reinf,24,'un renfort ne doit pas apparaître sur la sortie au bout de la salle');
assert.equal(enemies.find(e=>e.id==='reinforce_new').dungeonCell200,reinf);
assert.ok(renderCalls>=2,'la grille doit être rerendue après chaque repositionnement');
assert.equal(api.isAmbush({id:'d_evt_ambush'}),true);
assert.equal(api.isReinforcement({id:'d_evt_reinforce',name:'Renforts ennemis'}),true);
assert.equal(api.isCloseSpawnEvent({id:'d_evt_reinforce'}),true);
console.log('Dungeon Ambush/Reinforcement proximity V16.78.79: OK');
