const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const src=fs.readFileSync(path.join(root,'assets','gensrpg','gens-equipment-bonus-persistence-1678103.js'),'utf8');
const bridge=fs.readFileSync(path.join(root,'assets','gensrpg','gens-dungeon-hero-art-repair-167874.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
assert.doesNotThrow(()=>new Function(src),'equipment persistence syntax');
assert.match(src,/APP_VERSION="16\.78\.113"/);
assert.match(src,/loadDungeonItemOverrides/);assert.match(src,/saveCustomEquipment/);assert.match(src,/equipmentSummary/);assert.match(src,/equipmentCardStatsHtml/);
assert.match(src,/if\(storeCache\)return storeCache/,'runtime store must be memoized');
assert.match(src,/listRev\.get\(list\)===revision/,'list hydration must be cached');
assert.match(bridge,/gens-equipment-bonus-persistence-1678103\.js\?v=1678113/);
assert.match(sw,/gensrpg-cache-16\.78\.113-combat-profiler-fix/);
let custom=[{id:'custom_sword',name:'Épée custom',rpgBonuses:{}}],overrides={};const dungeon=[{id:'dng_sword',name:'Épée Dungeon',rpgBonuses:{}}],storage={};
const ctx={console,Math,JSON,setTimeout:()=>0,globalThis:null,localStorage:{getItem:k=>storage[k]??null,setItem:(k,v)=>{storage[k]=String(v)}},GensCleanRpgStats167874:{defs:()=>[{id:'force',name:'Force',icon:'💪'},{id:'necromancie',name:'Nécromancie',icon:'☠️'}],runtimeDefs:()=>[],def:id=>({force:{id:'force'},necromancie:{id:'necromancie'}}[id]||null)},loadCustomEquipment:()=>custom,saveCustomEquipment:list=>{custom=JSON.parse(JSON.stringify(list))},refreshCustomEquipmentIntoItems:()=>{},dungeonItems:()=>dungeon,ITEMS:dungeon,loadDungeonItemOverrides:()=>overrides,saveDungeonItemOverrides:o=>{overrides=JSON.parse(JSON.stringify(o))},ensureDungeonItems:()=>{}};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);vm.runInContext(src,ctx);
const api=ctx.GensEquipmentBonusPersistence1678103;assert.ok(api);
let r=api.persistBonuses('custom_sword',{force:3,necromancie:2});assert.equal(r.ok,true);assert.equal(r.kind,'custom');assert.equal(JSON.stringify(custom[0].rpgBonuses),JSON.stringify({force:3,necromancie:2}));
r=api.persistBonuses('dng_sword',{force:4});assert.equal(r.ok,true);assert.equal(r.kind,'override');assert.equal(JSON.stringify(overrides.dng_sword.rpgBonuses),JSON.stringify({force:4}));
console.log('V16.78.113 equipment persistence: save paths + runtime memoization OK');
