const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const cp=require('node:child_process');
const root=path.join(__dirname,'..');
const patcher=path.join(root,'tools','patch_generic_stat_grid_v167890.py');
const source=path.join(root,'index.html');
assert.ok(fs.existsSync(patcher));assert.ok(fs.existsSync(source));
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'gens-v167897-')),target=path.join(tmp,'index.html');
fs.copyFileSync(source,target);cp.execFileSync('python3',[patcher,target],{stdio:'pipe'});
const html=fs.readFileSync(target,'utf8');
assert.match(html,/gensCanonicalStatGridV167897/,'final build must contain the canonical renderer');
assert.match(html,/GENS_STAT_ALIAS_V167897=\{agility:"agilite",spirit:"esprit"\}/,'legacy editor ids must normalize to runtime ids');
assert.match(html,/function gensCanonicalActiveDefsV167897\(\)/);
assert.match(html,/host\.innerHTML=defs\.map/,'the grid must be generated from active definitions, not a fixed attribute map');
assert.match(html,/function gensChangeCanonicalStatV167897\(id,delta\)/);
assert.match(html,/state\.rpgStatSpent=Math\.max\(0,Number\(state\.rpgStatSpent\)\|\|0\)\+actual/,'spent points must stay numeric for Dungeon progression');
assert.match(html,/state\.rpgStatSpentById/,'per-stat refunds must be tracked separately from the numeric total');
assert.match(html,/gsrCustomStatDescription/);assert.match(html,/Influence : /);
assert.match(html,/dataset\.gensUnifiedStatGrid="167897"/);
assert.match(html,/GENSRPG_VERSION="16\.78\.97"/);
assert.match(html,/function renderDungeonAttributes\(\)\{return gensRenderCanonicalAttributesV167897\(\)\|\|renderDungeonAttributes__native167890/,'canonical renderer must own the final grid');
assert.match(html,/gensCurrentRpgProfileActiveV167894/,'active gameplay profile must remain authoritative');
const start=html.indexOf('/* gensCanonicalStatGridV167897'),end=html.indexOf('</script>',start);assert.ok(start>=0&&end>start);
const wrapper=html.slice(start,end);
assert.doesNotMatch(wrapper,/MutationObserver|setInterval|startDungeonCombat|enemyCells\s*=|dungeonRoom\s*=/,'stat renderer must not touch spatial/combat systems');
cp.execFileSync('python3',[patcher,target],{stdio:'pipe'});
const twice=fs.readFileSync(target,'utf8');
assert.equal((twice.match(/gensCanonicalStatGridV167897/g)||[]).length,1,'patch must be idempotent');
const site=process.argv[2]&&fs.existsSync(process.argv[2])?fs.readFileSync(process.argv[2],'utf8'):null;
if(site){assert.match(site,/gensCanonicalStatGridV167897/);assert.match(site,/GENSRPG_VERSION="16\.78\.97"/)}
console.log('GenSrpG canonical Dungeon stat grid V16.78.97 regression: OK');
