const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const editor=fs.readFileSync(path.join(root,'assets','gensrpg','gens-hero-editor-dynamic-167897.js'),'utf8');
const bridge=fs.readFileSync(path.join(root,'assets','gensrpg','gens-dungeon-hero-art-repair-167874.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
assert.doesNotThrow(()=>new Function(editor),'safe hero editor syntax');
assert.match(editor,/APP_VERSION="16\.78\.101"/);
assert.doesNotMatch(editor,/new\s+(?:R\.)?MutationObserver|\.observe\s*\(D\.documentElement/,'hero editor must never observe the global DOM');
assert.doesNotMatch(editor,/GENSRPG_VERSION\s*=/,'UI-only editor must not change global app version');
assert.match(bridge,/GenSrpG V16\.78\.105/,'always-loaded bridge must carry current stability layer');
assert.doesNotMatch(bridge,/MutationObserver|\.observe\s*\(/,'always-loaded bridge must not observe unrelated UI panels');
assert.match(bridge,/dungeon-grid-display-recovery-167856\.js\?v=1678100/,'always-loaded bridge must restore tactical grid recovery');
assert.match(bridge,/gens-hero-editor-dynamic-167897\.js\?v=1678101/,'always-loaded bridge must load canonical hero/stat consolidation layer');
assert.match(bridge,/gens-dungeon-hero-ingame-art-167898\.js\?v=1678100/,'always-loaded bridge must repair hero art in game');
assert.match(bridge,/gens-dungeon-sheet-art-stability-167899\.js\?v=1678100/,'always-loaded bridge must repair built-in hero art on the sheet');
assert.match(bridge,/gens-stat-upgrade-policy-167898\.js\?v=1678100/,'always-loaded bridge must load stat upgrade policy');
assert.match(bridge,/gens-dungeon-ui-cleanup-1678100\.js\?v=1678100/,'always-loaded bridge must load targeted UI cleanup');
assert.match(bridge,/gens-equipment-stat-cleanup-1678102\.js\?v=1678102/,'always-loaded bridge must load equipment stat cleanup');
assert.match(bridge,/gens-equipment-bonus-persistence-1678103\.js\?v=1678104/,'always-loaded bridge must load authoritative equipment bonus persistence');
assert.match(bridge,/gens-enemy-canonical-stats-1678105\.js\?v=1678105/,'always-loaded bridge must load canonical enemy stats module');
assert.match(bridge,/applyCustomHeroesMulti/,'hero art repair must run after late CHARS rebuild');
assert.match(bridge,/dng_aldren\.png/,'Aldren official art must remain hard-pinned');
assert.match(sw,/gensrpg-cache-16\.78\.105-enemy-stats-module/);
for(const critical of ['dungeon-grid-display-recovery-167856.js','dungeon-random-library-content-167832.js','dungeon-world-builder-167821.js','dng_aldren.png','gens-hero-editor-dynamic-167897.js','gens-dungeon-hero-ingame-art-167898.js','gens-dungeon-sheet-art-stability-167899.js','gens-stat-upgrade-policy-167898.js','gens-dungeon-ui-cleanup-1678100.js','gens-equipment-stat-cleanup-1678102.js','gens-equipment-bonus-persistence-1678103.js','gens-enemy-canonical-stats-1678105.js'])assert.ok(sw.includes(critical),'critical cache entry missing: '+critical);
require('./gens_enemy_stats_module_v1678105.test.cjs');
require('./gens_aldren_post_rebuild_v1678105.test.cjs');
require('./dungeon_grid_display_recovery_v167856.test.cjs');
require('./gens_dungeon_hero_art_repair_v167874.test.cjs');
require('./gens_v167898_guard.test.cjs');
require('./gens_v167899_ui_sheet_guard.test.cjs');
require('./gens_v1678100_ui_cleanup_guard.test.cjs');
require('./dungeon_world_runtime_v167823.test.cjs');
console.log('V16.78.105 stability guard: grids + post-rebuild Aldren art + optional canonical enemy stats + existing UI stability OK');
