const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'..','assets','gensrpg','gens-dungeon-hero-art-repair-167874.js'),'utf8');
const stats=fs.readFileSync(path.join(__dirname,'..','assets','gensrpg','gens-rpg-stats-clean-167874.js'),'utf8');
assert.match(src,/GenSrpG V16\.78\.93/,'cleanup bridge must carry V16.78.93');
assert.match(src,/rpgBaseHp/,'legacy HP editor card must be targeted');
assert.match(src,/rpgBaseMana/,'legacy Mana editor card must be targeted');
assert.match(src,/rpgPhysicalFormula/,'legacy characteristic modifiers card must be targeted');
assert.match(src,/closest\?\.\("\.smodCard"\)/,'cleanup must hide the old UI card, not remove engine data');
assert.match(src,/card\.hidden=true/,'obsolete editor cards must be hidden');
assert.match(src,/cleanupLegacyRpgEditor/,'cleanup must run from the existing always-loaded bridge');
assert.match(stats,/APP_VERSION="16\.78\.95"/,'single stats module must carry the current V16.78.95 stat engine');
assert.match(stats,/DUNGEON_DEFAULT_ATTRIBUTES/,'canonical runtime link must remain intact');
assert.match(stats,/legacyEffectsMigrated94/,'legacy coefficient migration must remain active');
assert.match(src,/gens-hero-editor-dynamic-167896\.js\?v=167896/,'V16.78.96 hero editor bridge must be loaded');
assert.doesNotMatch(src,/delete\s+R\.|delete\s+.*rpgBaseHp|delete\s+.*rpgBaseMana/,'visual cleanup must not delete runtime settings');
console.log('GenSrpG editor cleanup: old HP/Mana/modifier UI hidden, V16.78.95 stats engine preserved, V16.78.96 hero editor bridge loaded');
