const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const file=path.join(root,'assets','gensrpg','gens-custom-stat-runtime-profile-167889.js');
const src=fs.readFileSync(file,'utf8');
assert.doesNotThrow(()=>new Function(src),'V16.78.97 canonical stat authority must be valid JS');
assert.match(src,/APP_VERSION="16\.78\.97"/);
assert.match(src,/ALIASES=\{agility:"agilite",spirit:"esprit"\}/);
assert.match(src,/canonicalStatAuthorityV167897/);
assert.match(src,/api\.renderHero=function\(\)\{return true\}/,'legacy exported secondary renderer must be neutralized');
assert.match(src,/renderPrimaryList/,'editor primary list must be rebuilt from canonical definitions');
assert.doesNotMatch(src,/function renderUnifiedStats\(/,'V16.78.96 overlay renderer must be removed');

const profile={id:'dungeon',gameStyle:'dungeon',rpgUniverse:{stats:{active:['force','agility','spirit','furtivite'],customStats:[{id:'furtivite',name:'Furtivité',icon:'🥷',visible:true,editMode:'points',description:'Discrétion'}]}}};
let store=[profile];
const primary={dataset:{},listeners:{},addEventListener(n,fn){this.listeners[n]=fn},innerHTML:''};
const custom={dataset:{},listeners:{},addEventListener(n,fn){this.listeners[n]=fn},querySelector(){return null}};
const modal={style:{display:'none'}};
const document={readyState:'complete',getElementById:id=>id==='rpgUniverseEditorModal'?modal:id==='rpgStatsList'?primary:id==='gcs167879Box'?custom:null};
const api={renderEditor:()=>true};
const sandbox={console,document,window:null,globalThis:null,GensCustomStats167879:api};sandbox.window=sandbox;sandbox.globalThis=sandbox;
sandbox.loadGameProfiles=()=>store;sandbox.saveGameProfiles=x=>{store=x};sandbox.getActiveGameProfile=()=>store[0];sandbox.currentRpgProfile=()=>store[0];sandbox.renderRpgUniverseEditor=()=>true;sandbox.renderDungeonAttributes=()=>true;sandbox.renderDungeonHeroStats=()=>true;sandbox.DungeonCore01={render(){},show(){}};
vm.runInNewContext(src,sandbox);
const bridge=sandbox.GensCustomStatRuntimeProfile167889,s=bridge.profileStats(store[0]);
assert.equal(s.active.includes('agility'),false);assert.equal(s.active.includes('spirit'),false);
assert.equal(s.active.includes('agilite'),true);assert.equal(s.active.includes('esprit'),true);
for(const id of ['force','agilite','intelligence','esprit','endurance','initiative','furtivite'])assert.ok(s.customStats.some(d=>d.id===id),'missing canonical definition '+id);
assert.ok(primary.innerHTML.includes('value="agilite"'));assert.ok(primary.innerHTML.includes('value="esprit"'));
assert.equal(sandbox.GensCustomStats167879.isActive('agility'),true,'legacy alias lookup must resolve to canonical Agilité');
assert.equal(sandbox.GensCustomStats167879.isActive('spirit'),true,'legacy alias lookup must resolve to canonical Esprit');
const site=process.argv[2]&&fs.existsSync(process.argv[2])?fs.readFileSync(process.argv[2],'utf8'):null;
if(site)assert.match(site,/gens-custom-stat-runtime-profile-167889\.js\?v=167889/,'final site must load canonical stat authority');
console.log('GenSrpG canonical stat authority V16.78.97: OK');
