const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const file=path.join(root,'assets','gensrpg','gens-custom-stats-167881.js');
const bridgeFile=path.join(root,'assets','gensrpg','gens-stat-help-extension-167881.js');
const src=fs.readFileSync(file,'utf8');
const bridge=fs.readFileSync(bridgeFile,'utf8');
assert.doesNotThrow(()=>new Function(src),'custom stat engine must stay syntactically valid');
assert.doesNotThrow(()=>new Function(bridge),'RPG rule bridge must stay syntactically valid');
assert.match(src,/APP_VERSION="16\.78\.81"/);
assert.match(bridge,/APP_VERSION="16\.78\.82"/);
assert.match(src,/function syncPrimaryList/,'custom stats must join the canonical Characteristics principales selector');
assert.match(src,/p\.rpgUniverse\.stats\.customStats=next/,'customStats must remain the definition source of truth');
assert.match(src,/function effectTotals/,'runtime modifiers must be calculated from definitions on demand');
assert.match(bridge,/statAbilityLinks/,'stat-to-ability links must store references, not duplicate ability definitions');
assert.match(bridge,/rpgAbilityRefs/,'equipment must link to ability-library IDs');
assert.match(bridge,/decorateAbilityScaling/,'ability scaling editor must accept the shared stat catalog');
assert.match(bridge,/grb167882WeaponStat/,'existing equipment editor must receive a configurable stat selector');
assert.match(bridge,/dungeonAttributeValue\(ref\)/,'core-stat consumers must use the final modified stat value');
assert.match(bridge,/function calculatedTalentAmount/,'ability damage must use the unified raw-damage calculation');
assert.match(bridge,/hitDamages:\[raw\]/,'ability damage must enter the existing damage resolver as raw damage');
assert.doesNotMatch(bridge,/finalAmount=.*gensElementMultiplier/,'ability bridge must not pre-apply element multiplier before the canonical resolver');
assert.doesNotMatch(bridge,/enemyCells\s*=|positions\s*=|dungeonRoom\s*=|startDungeonCombat\s*=/,'rule bridge must not rewrite movement, enemy placement or combat start');
const profile={id:'demo',name:'Dungeon demo',rpgUniverse:{stats:{active:['force','epuisement'],customStats:[{id:'epuisement',name:'Épuisement',kind:'gauge',min:0,max:100,defaultValue:0,effects:[{when:'gte',threshold:50,target:'attribute:force',mode:'flat',value:-2}]}]},exploration:{},rules:{statAbilityLinks:[{id:'l1',enabled:true,statId:'epuisement',when:'gte',threshold:50,abilityId:'a1'}]}}};
const hero={customStats:{epuisement:60},rpgAttributes:{force:10,epuisement:60}};
const ability={id:'a1',name:'Frappe test',type:'active',effects:[{kind:'damage',base:3,scaleAttribute:'epuisement',scaleCoeff:.1,damageType:'physical'}],usageScopes:['rpgHero']};
const sandbox={console,Math,Date,setTimeout:()=>0,clearTimeout:()=>{},localStorage:{getItem:()=>null,setItem:()=>{}},window:null,globalThis:null,document:null};
sandbox.window=sandbox;sandbox.globalThis=sandbox;sandbox.current='h';sandbox.currentRpgProfile=()=>profile;sandbox.loadGameProfiles=()=>[profile];sandbox.saveGameProfiles=()=>{};sandbox.loadState=()=>hero;sandbox.key=id=>'hero_'+id;sandbox.dungeonAttributeValue=id=>Number(hero.rpgAttributes[id])||0;sandbox.loadAbilityLibrary=()=>[ability];sandbox.gensAbilityUsages=a=>a.usageScopes;sandbox.loadDungeonRpgRules=()=>({physicalDamageFormula:'step',physicalDamageStep:10,physicalDamageGain:1,magicDamageFormula:'step',magicDamageStep:10,magicDamageGain:1});
vm.runInNewContext(src,sandbox);
sandbox.GensCustomStats167879.installEffectHooks();
vm.runInNewContext(bridge,sandbox);
assert.equal(sandbox.GensCustomStats167879.isActive('epuisement'),true);
assert.equal(sandbox.dungeonAttributeValue('force'),8,'Épuisement >= 50 must reduce Force through the canonical custom-stat engine');
assert.equal(sandbox.GensRpgRuleBridge167882.grantedAbilities('h')[0].id,'a1','threshold link must grant the referenced library ability');
const raw=sandbox.GensRpgRuleBridge167882.calculatedTalentAmount('h',ability.effects[0]);
assert.equal(raw,9,'raw ability damage must use final modified Force: base 3 + Épuisement scaling 6, with Force 8 below the +1/10 threshold');
const site=process.argv[2]&&fs.existsSync(process.argv[2])?fs.readFileSync(process.argv[2],'utf8'):null;
if(site){
 assert.match(site,/gens-custom-stats-167881\.js\?v=167881/);
 assert.match(site,/gens-stat-help-extension-167881\.js\?v=167881/);
 assert.doesNotMatch(site,/gens-custom-stats-167879\.js\?v=167879/);
}
console.log('GenSrpG custom stats + unified RPG rules V16.78.82 regression: OK');
