const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const cp=require('node:child_process');
const root=path.join(__dirname,'..');
const patcher=path.join(root,'tools','patch_generic_stat_grid_v167890.py');
const source=path.join(root,'index.html');
assert.ok(fs.existsSync(patcher));assert.ok(fs.existsSync(source));
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'gens-v167892-')),target=path.join(tmp,'index.html');
fs.copyFileSync(source,target);cp.execFileSync('python3',[patcher,target],{stdio:'pipe'});
const html=fs.readFileSync(target,'utf8');
assert.match(html,/function renderDungeonAttributes__native167890\(\)\{/);
assert.match(html,/function renderDungeonHeroStats__native167890\(\)\{/);
assert.match(html,/function gensCurrentHeroIdV167891\(\)\{/,'classic script must expose the lexical current hero');
assert.match(html,/return current\?String\(current\)/,'getter must read the lexical hero selected by the native sheet');
assert.match(html,/if\(heroId\)globalThis\.current=heroId/,'native render must synchronize the current hero before external stat logic runs');
assert.match(html,/function gensRenderActiveCustomStatsV167892\(\)\{/,'V16.78.92 must own the complete active custom-stat card render');
assert.match(html,/getActiveGameProfile\?\.\(\)/,'custom cards must read one active gameplay profile snapshot');
assert.match(html,/active=new Set\(\(Array\.isArray\(stats\.active\)/,'activation list must be the source of truth');
assert.match(html,/filter\(def=>def&&def\.id&&active\.has\(String\(def\.id\)\)\)/,'every active custom definition must be rendered');
assert.doesNotMatch(html,/filter\(def=>[^\n]*visible/,'main characteristic grid must not silently hide an active stat behind a second visibility flag');
assert.match(html,/gsrCustomStatDescription/,'the user-authored stat description must be displayed');
assert.match(html,/Influence : /,'configured derived links must be shown separately from the authored description');
assert.match(html,/gensActiveCustomStats=String\(list\.length\)/,'the rendered card count must be exposed for regression/debug checks');
assert.match(html,/dataset\.gensUnifiedStatGrid="167892"/);
assert.match(html,/GENSRPG_VERSION="16\.78\.92"/);
assert.match(html,/api\)api\.patchSheetTexts\?\.\(\);[\s\S]*gensRenderActiveCustomStatsV167892\(\)/,'derived texts must refresh first, complete custom cards last');
const start=html.indexOf('/* GenSrpG V16.78.92');
const end=html.indexOf('</script>',start);
assert.ok(start>=0&&end>start);
assert.doesNotMatch(html.slice(start,end),/MutationObserver|setInterval|setTimeout|createElement\(["']script["']\)|enemyCells\s*=|dungeonRoom\s*=|startDungeonCombat/);
cp.execFileSync('python3',[patcher,target],{stdio:'pipe'});
const twice=fs.readFileSync(target,'utf8');
assert.equal((twice.match(/function gensCurrentHeroIdV167891\(\)/g)||[]).length,1);
assert.equal((twice.match(/function gensRenderActiveCustomStatsV167892\(\)/g)||[]).length,1);
assert.equal((twice.match(/function gensUnifiedStatGridV167890\(\)/g)||[]).length,1);
const site=process.argv[2]&&fs.existsSync(process.argv[2])?fs.readFileSync(process.argv[2],'utf8'):null;
if(site){
  assert.match(site,/gensRenderActiveCustomStatsV167892/);
  assert.match(site,/gsrCustomStatDescription/);
  assert.match(site,/gensActiveCustomStats/);
  assert.match(site,/GENSRPG_VERSION="16\.78\.92"/);
}
console.log('GenSrpG complete active custom-stat cards V16.78.92 regression: OK');
