const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const file=path.join(root,'assets','gensrpg','gens-custom-stat-runtime-profile-167889.js');
const src=fs.readFileSync(file,'utf8');
assert.doesNotThrow(()=>new Function(src),'V16.79.01 RPG stat service must be valid JS');
assert.match(src,/APP_VERSION="16\.79\.01"/);
assert.match(src,/SCHEMA="rpgStatServiceV167901"/);
assert.match(src,/ALIASES=\{agility:"agilite",spirit:"esprit"\}/);
assert.match(src,/function definitions\(\)\{return statsRoot\(\)\?\.customStats\|\|\[\]\}/);
assert.match(src,/function value\(hero,id\)/);
assert.match(src,/equipmentBonus\(id\)\+talentBonus\(id\)\+malus\(id,hero\)/,'all authored stats must receive the same effective-value pipeline');
assert.match(src,/function renderSheet\(\)/);
assert.match(src,/definitions\(\)\.filter\(d=>d\.visible&&isActive\(d\.id\)\)/,'sheet must be generated from active registry definitions, not a hard-coded stat list');
assert.match(src,/old\.style\.display="none"/,'legacy custom-stat editor must be hidden');
assert.match(src,/primary\.innerHTML="";primary\.style\.display="none"/,'legacy primary stat list must be retired');
assert.match(src,/GensRpgStatService167901/,'single stat service API missing');
assert.doesNotMatch(src,/canonicalStatAuthorityV167898/,'old canonical overlay authority must be gone');
assert.doesNotMatch(src,/gensRenderCanonicalAttributesV167897/,'old canonical renderer must be gone');
const site=process.argv[2]&&fs.existsSync(process.argv[2])?fs.readFileSync(process.argv[2],'utf8'):null;
if(site)assert.match(site,/gens-custom-stat-runtime-profile-167889\.js\?v=167889/,'final site must load the RPG stat service');
console.log('GenSrpG single RPG stat service V16.79.01 source authority: OK');
