const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const src=fs.readFileSync(path.join(root,'assets','gensrpg','gens-stat-rules-help-167880.js'),'utf8');
assert.doesNotThrow(()=>new Function(src),'stat rule/help module must stay syntactically valid');
assert.match(src,/APP_VERSION="16\.78\.80"/);
assert.match(src,/Raccordements de gameplay/,'editor must expose gameplay links');
assert.match(src,/plus_vs_dc/,'classic die + stat vs difficulty rule must exist');
assert.match(src,/roll_under/,'roll-under rule must exist');
assert.match(src,/percent/,'percentage rule must exist');
assert.match(src,/gensrpg:stat-test/,'tests must emit a generic gameplay event');
assert.match(src,/applyEffect/,'result effects must be applicable');
assert.match(src,/GensCustomStats167879/,'must reuse the generic custom stat layer');
assert.match(src,/Mode de modification/,'contextual help must explain edit modes');
assert.match(src,/Type : Score ou Jauge/,'contextual help must explain stat types');
assert.match(src,/gsh167880Modal/,'help must open as an explicit contextual panel');
assert.doesNotMatch(src,/positions\s*=|enemyCells\s*=|saveActiveEnemies|startDungeonCombat/,'rule/help layer must not mutate movement, enemy placement or combat start');
const site=process.argv[2]&&fs.existsSync(process.argv[2])?fs.readFileSync(process.argv[2],'utf8'):null;
if(site)assert.match(site,/gens-stat-rules-help-167880\.js\?v=167880/,'built site must load the stat rule/help module');
console.log('GenSrpG stat rule links + contextual help V16.78.80 regression: OK');
