'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const doc=read('docs/GENSRPG_PHASE8_TACTICAL_FIRST_REQUEST_ACTIVATION_CHARACTERIZATION.md');
const entry=read('assets/gensrpg/tactical/entry-v1.js');
const bridge=read('assets/gensrpg/gens-rpg-tactical-combat-v2-bridge.js');
assert.match(doc,/l'entrée publique charge immédiatement engine, adapter, rules, integration, UI puis Bridge/,'baseline eager state must remain documented');
assert.match(doc,/modules-missing/,'baseline cold failure must remain documented');
assert.match(entry,/const facadeFile="assets\/gensrpg\/gens-rpg-tactical-combat-v2-bridge\.js"/,'current bootstrap must now be facade-first');
assert.match(entry,/function activate\(onReady\)/,'current entry must expose cold activation');
assert.match(bridge,/pending:true,reason:"tactical-activating"/,'current Bridge must accept a cold request');
const Bridge=require(path.join(root,'assets','gensrpg','gens-rpg-tactical-combat-v2-bridge.js'));
let opened=0;const enemy={id:'e1',enemyId:'goblin',hp:5};
const rt={localStorage:{getItem:k=>k==='gensrpg_session_family_guard_v1'?'adventure':null},getActiveGameProfile:()=>({gameStyle:'dungeon'}),GensRpgTacticalCombatV2:{},GensRpgTacticalCombatV2Adapter:{participants:()=>['h1'],enteredParticipants:(_rt,ids)=>ids,activeEnemies:()=>[enemy]},GensRpgTacticalCombatV2Ui:{getBattle:()=>null,openCurrentEncounter(){opened++;return {actors:[],winner:null}}},dispatchEvent(){},showToast(){},console};
const out=Bridge.requestCombat(rt,{enemyIds:['e1'],reason:'manual',entry:'phase8-warm-characterization'});
assert.equal(out?.ok,true);assert.equal(out?.pending,undefined);assert.equal(opened,1);
console.log(JSON.stringify({scenario:'Phase 8 Tactical first-request activation characterization',baselinePreservedInDoc:true,current:{bootstrap:'Bridge facade only',coldRequest:'activation-pending',warmRequest:'synchronous-ok'}},null,2));
