const fs=require('fs'),vm=require('vm'),assert=require('assert');
const perf=fs.readFileSync('assets/gensrpg/gens-combat-runtime-performance-1678110.js','utf8');
const dice=fs.readFileSync('assets/gensrpg/gens-dice-performance-1678108.js','utf8');
assert.match(perf,/APP_VERSION="16\.78\.115"/);
assert.match(perf,/dungeonAttributeValue/);
assert.match(perf,/GensCleanRpgStats167874/);
assert.match(perf,/dungeonEnemyRpgStats/);
assert.doesNotMatch(perf,/queueMicrotask/,'V115 cache must survive the current JS turn');
assert.doesNotMatch(dice,/[◆✦★⭐]/,'Le dé ne doit plus afficher de placeholder étoile/diamant');
assert.match(dice,/makeReel\(6,finalValue/,'D6 must use the smooth reel path');
assert.match(dice,/APP_VERSION="16\.78\.112"/);
assert.match(dice,/WATCHDOG_MS=650/);
assert.match(dice,/REEL_STEPS=11/);
assert.doesNotMatch(dice,/scheduleTicks|TICK_COUNT/,'V112 must not reintroduce choppy numeric DOM ticks');
let calls=0,valueCalls=0,enemyCalls=0;
const sandbox={console,setTimeout:(fn)=>{fn();return 1},clearTimeout(){},Promise,current:'hero1',dungeonAttributeValue(id){calls++;return id==='force'?12:3},dungeonEnemyRpgStats(def){enemyCalls++;return {force:def.force||1}},GensCleanRpgStats167874:{value(hero,id){valueCalls++;return hero==='hero1'&&id==='force'?12:0},runtimeDefs(){return [{id:'force'}]}},renderDungeonCombatRound(){},__dc302RenderCombat(){},__dc214RenderCombat(){},applyDungeonAttackDamage(){},silentHeroDamage023(){},changeDungeonAttribute(){},dc214Equip(){},dc214Reload(){},save(){},saveState(){},saveActiveEnemies(){},saveDungeonHeroState(){},saveDungeonHeroStats(){}};
sandbox.window=sandbox;sandbox.globalThis=sandbox;
vm.createContext(sandbox);vm.runInContext(perf,sandbox);
for(let i=0;i<50;i++)assert.equal(sandbox.dungeonAttributeValue('force'),12);
for(let i=0;i<50;i++)assert.equal(sandbox.GensCleanRpgStats167874.value('hero1','force'),12);
const e={force:7};for(let i=0;i<50;i++)assert.equal(sandbox.dungeonEnemyRpgStats(e).force,7);
assert.equal(calls,1);assert.equal(valueCalls,1);assert.equal(enemyCalls,1);
assert.ok(sandbox.GensCombatRuntimePerformance1678110);
console.log('V16.78.115 combat runtime performance guard + V112 compositor dice OK');
