const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const src=fs.readFileSync(path.join(root,'assets','gensrpg','gens-combat-flow-1678111.js'),'utf8');
assert.doesNotThrow(()=>new Function(src));
assert.match(src,/APP_VERSION="16\.78\.114"/);
assert.match(src,/modernRuntime/);
assert.match(src,/attackResultOpen/);
assert.doesNotMatch(src,/reinstall\(\)/,'V114 must not keep re-installing wrappers');

let legacy=0,renders=0;const raf=[];const modal={classList:{contains:n=>n==='open'}};
const context={console,Promise,setTimeout(){throw new Error('no timer expected in modern mode')},requestAnimationFrame:fn=>raf.push(fn),document:{getElementById:id=>id==='attackDiceModal'?modal:null}};
context.window=context;context.globalThis=context;context.__dc214RenderCombat=()=>{};context.__dc302RenderCombat=()=>{};context.dungeonRunAi156=()=>legacy++;context.dungeonAdvanceTurn156=()=>{};context.renderDungeonCombatRound=()=>renders++;
const oldRunner=context.dungeonRunAi156,oldAdvance=context.dungeonAdvanceTurn156;
vm.createContext(context);vm.runInContext(src,context);
assert.equal(context.dungeonRunAi156,oldRunner);assert.equal(context.dungeonAdvanceTurn156,oldAdvance);
context.renderDungeonCombatRound();context.renderDungeonCombatRound();assert.equal(renders,0);assert.equal(raf.length,1);raf[0]();assert.equal(renders,1);
console.log('V16.78.114 combat flow: modern timeline isolated, hot render coalesced OK');
