'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const {execFileSync}=require('node:child_process');
const root=path.join(__dirname,'..');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const external='assets/gensrpg/capture/builtin-seed-v1.js';
const script=fs.readFileSync(path.join(root,external),'utf8');
const tag='<script id="builtinMonsterCapture162" src="'+external+'?v=1"></script>';
assert.equal(index.split(tag).length-1,1,'Seed must load once, synchronously at original location');
assert.equal(index.includes('<script id="builtinMonsterCapture162">'),false,'No duplicate legacy inline V16.162 seed');
assert.ok(index.indexOf(tag)>index.indexOf('<script id="captureFix144"') || index.indexOf(tag)>index.indexOf('<script id="captureAbilityTruth144"'),'Seed remains after existing Capture combat compatibility');
assert.ok(index.indexOf(tag)<index.indexOf('id="dungeonCore071ColdStart"'),'Seed remains ahead of legacy Dungeon cold start');
assert.ok(script.startsWith('\n(function(){\n"use strict";'),'Original seed IIFE and strict scope unchanged');
assert.ok(script.includes('window.ensureBuiltinMonsterCapture162=function()'));
assert.ok(script.includes('const merged=mc162MergeById(current,MC162_ENTITIES)'),'Non-destructive Capture creature merge preserved');
assert.ok(script.includes('const merged=mc162MergeById(current,MC162_ABILITIES)'),'Non-destructive Capture ability merge preserved');
assert.ok(script.includes('if(localStorage.getItem(k)==null)localStorage.setItem(k,v)'),'User settings win over showcase defaults');
assert.ok(script.includes('document.addEventListener("DOMContentLoaded",()=>setTimeout(ensureBuiltinMonsterCapture162,60))'),'Original post-DOM seed retained');
execFileSync(process.execPath,['scripts/gensrpg_capture_seed_extract_v1.cjs','--verify'],{cwd:root,stdio:'pipe'});
console.log(JSON.stringify({scenario:'Monster Capture V16.162 physical seed extraction',external,bytes:Buffer.byteLength(script),singleAuthority:true,rollbackByteExact:true}));
