const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=path.join(__dirname,'..');
const sheetSrc=fs.readFileSync(path.join(root,'assets','gensrpg','gens-dungeon-sheet-art-stability-167899.js'),'utf8');
const bridge=fs.readFileSync(path.join(root,'assets','gensrpg','gens-dungeon-hero-art-repair-167874.js'),'utf8');
const policy=fs.readFileSync(path.join(root,'assets','gensrpg','gens-stat-upgrade-policy-167898.js'),'utf8');
const ui=fs.readFileSync(path.join(root,'assets','gensrpg','gens-dungeon-ui-cleanup-1678100.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
assert.doesNotThrow(()=>new Function(sheetSrc),'sheet art stability syntax');
assert.match(sheetSrc,/APP_VERSION="16\.78\.99"/);
assert.doesNotMatch(sheetSrc,/MutationObserver/,'sheet repair must use lifecycle hooks, not a global observer');
assert.doesNotMatch(bridge,/MutationObserver|\.observe\s*\(/,'always-loaded visual bridge must not observe the whole app DOM');
assert.match(bridge,/gens-dungeon-sheet-art-stability-167899\.js\?v=1678100/,'bridge must load in-game sheet art repair');
assert.match(bridge,/gens-dungeon-ui-cleanup-1678100\.js\?v=1678113/,'bridge must load V16.78.113 optimized targeted cleanup');
assert.match(ui,/APP_VERSION="16\.78\.113"/);
const uiHooks=(ui.match(/function hookAll\(\)\{[^\n]+/)||[''])[0];
assert.ok(!uiHooks.includes('renderDungeonHeroStats')&&!uiHooks.includes('renderDungeonAttributes'),'sheet/UI compatibility layer must stay out of combat-hot stat rendering');
assert.match(policy,/APP_VERSION="16\.78\.99"/);
assert.match(policy,/id==="movement"\?10:1/,'Movement must still cost 10 points for +1 by default');
assert.match(policy,/data-upgrade-policy-badge/,'stat card must show a visible upgrade-cost badge');
assert.match(policy,/\+1 = /,'stat card must state the cost directly inside the box');
assert.match(sw,/gensrpg-cache-16\.78\.113-combat-profiler-fix/);
assert.ok(sw.includes('gens-dungeon-sheet-art-stability-167899.js'),'sheet repair must be in PWA cache');
assert.ok(sw.includes('gens-dungeon-ui-cleanup-1678100.js'),'targeted cleanup must be in PWA cache');

let imgSrc='assets/old/aldren-placeholder.png';
const img={id:'charImage',className:'heroPortrait',alt:'',title:'',hidden:true,style:{display:'none',visibility:'hidden'},getAttribute(k){if(k==='src')return imgSrc;return null},setAttribute(k,v){if(k==='src')imgSrc=v;this[k]=v},removeAttribute(){}};
const sheet={textContent:'Aldren',getAttribute(){return null},querySelectorAll(sel){if(sel==='img'||/charImage|heroPortrait|heroAvatar|characterPortrait/.test(sel))return [img];return []}};
const document={readyState:'loading',addEventListener(){},querySelectorAll(sel){return /#sheet/.test(sel)?[sheet]:[]}};
const ctx={console,document,current:'dungeon_aldren',setTimeout,clearTimeout};ctx.window=ctx;ctx.globalThis=ctx;
vm.createContext(ctx);vm.runInContext(sheetSrc,ctx,{filename:'gens-dungeon-sheet-art-stability-167899.js'});
assert.ok(ctx.GensDungeonSheetArtStability167899,'sheet art API must be exposed');
assert.ok(ctx.GensDungeonSheetArtStability167899.repairSheet()>0,'sheet repair must actively repair Aldren');
assert.equal(imgSrc,'assets/dungeon/creatures/dng_aldren.png');
assert.equal(img.hidden,false);
assert.equal(img.style.display,'');
assert.equal(img.style.visibility,'visible');
console.log('V16.78.113 compatibility guard: Aldren sheet art + visible stat cost + combat-safe UI cleanup OK');
