'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const src=fs.readFileSync(path.join(__dirname,'..','assets','gensrpg','gens-equipment-stat-cleanup-1678102.js'),'utf8');
assert.match(src,/APP_VERSION="16\.78\.102\.1"/,'hotfix version');
assert.match(src,/const equipmentBonusCache=new Map\(\)/,'equipment bonus cache must exist');
assert.match(src,/function invalidateEquipmentBonusCache\(\)/,'cache invalidation must exist');
assert.match(src,/equipmentBonusCache\.get\(cacheKey\)/,'cached equipment bonus path must exist');
assert.match(src,/CACHE_TTL_MS=120/,'cache must stay short-lived');
let equippedCalls=0;
const item={id:'blade',evolution:{enabled:true,levels:[{level:2,xp:10,rpgBonuses:{force:3}}]}};
const sandbox={console,setTimeout:()=>0,clearTimeout:()=>{},globalThis:null,document:{readyState:'complete',getElementById:()=>null,querySelectorAll:()=>[],addEventListener:()=>{},__gensSetCanon102:false},performance:{now:(()=>{let n=0;return()=>n+=1})()},GensCleanRpgStats167874:{runtimeDefs:()=>[],def:()=>null},state:{xp:20},current:'hero',dungeonEquippedItems:()=>{equippedCalls++;return [item]},dungeonEquipmentBonus:()=>5};
sandbox.globalThis=sandbox;vm.createContext(sandbox);vm.runInContext(src,sandbox);
assert.equal(sandbox.dungeonEquipmentBonus('force'),8);
assert.equal(sandbox.dungeonEquipmentBonus('force'),8);
assert.equal(equippedCalls,1,'second identical combat lookup must reuse cached equipped items');
sandbox.GensEquipmentStatCleanup1678102.invalidateEquipmentBonusCache();
assert.equal(sandbox.dungeonEquipmentBonus('force'),8);
assert.equal(equippedCalls,2,'explicit invalidation must force refresh');
console.log('GenSrpG V16.78.102.1 equipment combat cache: OK');
