const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const ui=fs.readFileSync(path.join(root,'assets/gensrpg/gens-dungeon-ui-cleanup-1678100.js'),'utf8');
const eq=fs.readFileSync(path.join(root,'assets/gensrpg/gens-equipment-bonus-persistence-1678103.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
assert.match(ui,/APP_VERSION="16\.78\.113"/);
const hookAll=(ui.match(/function hookAll\(\)\{[^\n]+/)||[''])[0];
assert.ok(hookAll,'UI hookAll exists');
assert.ok(!hookAll.includes('renderDungeonHeroStats')&&!hookAll.includes('renderDungeonAttributes'),'combat-hot stat renderers must never schedule UI cleanup');
assert.doesNotMatch(ui,/tries\+\+<60|setTimeout\(retry,100\)/,'UI cleanup must not poll/repaint for 6 seconds');
assert.doesNotMatch(ui,/setTimeout\(\(\)=>\{try\{run\(\)/,'UI cleanup must not schedule duplicate delayed scans');
assert.match(eq,/APP_VERSION="16\.78\.113"/);
assert.match(eq,/if\(storeCache\)return storeCache/,'equipment store must stay parsed in memory');
assert.match(eq,/listRev\.get\(list\)===revision/,'equipment list hydration must be revision-cached');
assert.doesNotMatch(eq,/tries\+\+<40|setTimeout\(retry,100\)/,'equipment bridge must not poll for 4 seconds');
assert.match(sw,/gensrpg-cache-16\.78\.113-combat-profiler-fix/);
let gets=0,sets=0;
const storage={getItem(){gets++;return JSON.stringify({sword:{force:2}})},setItem(){sets++}};
const sandbox={console,window:null,globalThis:null,localStorage:storage,setTimeout(){return 1},document:null,GensCleanRpgStats167874:{def(id){return {id}},defs(){return [{id:'force',name:'Force'}]}}};sandbox.window=sandbox;sandbox.globalThis=sandbox;
vm.createContext(sandbox);vm.runInContext(eq,sandbox);
const api=sandbox.GensEquipmentBonusPersistence1678103;assert.ok(api);
const list=[{id:'sword'},{id:'shield'}];
for(let i=0;i<200;i++)api.hydrateList(list);
assert.equal(gets,1,'200 combat-time hydration reads must parse localStorage once');
assert.equal(list[0].rpgBonuses.force,2);
console.log('V16.78.113 hot-path: no combat UI scans + cached equipment hydration OK');