const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'..','assets','gensrpg','gens-dungeon-hero-art-repair-167874.js'),'utf8');
const stats=fs.readFileSync(path.join(__dirname,'..','assets','gensrpg','gens-rpg-stats-clean-167874.js'),'utf8');
assert.match(src,/GenSrpG V16\.78\.114\.11/,'cleanup/stability bridge must stay on the validated V16.78.114.11 visual authority');
assert.match(src,/rpgBaseHp/,'legacy HP editor card must be targeted');
assert.match(src,/rpgBaseMana/,'legacy Mana editor card must be targeted');
assert.match(src,/rpgPhysicalFormula/,'legacy characteristic modifiers card must be targeted');
assert.match(src,/closest\?\.\("\.smodCard"\)/,'cleanup must hide the old UI card, not remove engine data');
assert.match(src,/card\.hidden=true/,'obsolete editor cards must be hidden');
assert.match(src,/cleanupLegacyRpgEditor/,'cleanup must run from the existing always-loaded bridge');
assert.match(src,/hcRenderRpgStatsUsage/,'RPG stats usage cleanup must stay tied to its explicit hero-editor lifecycle');
assert.match(src,/openHeroCreator/,'hero editor cleanup must be tied to its explicit lifecycle');
assert.doesNotMatch(src,/MutationObserver|\.observe\s*\(/,'cleanup bridge must not observe unrelated UI panels globally');
assert.match(stats,/APP_VERSION="16\.78\.114\.7"/,'single stats module must remain on validated V16.78.114.7 canonical engine');
assert.match(stats,/DUNGEON_DEFAULT_ATTRIBUTES/,'canonical runtime link must remain intact');
assert.match(stats,/legacyEffectsMigrated94/,'legacy hidden coefficients must remain neutralized');
assert.doesNotMatch(src,/delete\s+R\.|delete\s+.*rpgBaseHp|delete\s+.*rpgBaseMana/,'visual cleanup must not delete runtime settings');
console.log('GenSrpG V16.78.114.11 scoped editor cleanup/stability bridge + V16.78.114.7 canonical stats engine: OK');