const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const editor=fs.readFileSync(path.join(root,'assets','gensrpg','gens-hero-editor-dynamic-167897.js'),'utf8');
const bridge=fs.readFileSync(path.join(root,'assets','gensrpg','gens-dungeon-hero-art-repair-167874.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
assert.doesNotThrow(()=>new Function(editor),'safe hero editor syntax');
assert.match(editor,/APP_VERSION="16\.78\.97"/);
assert.doesNotMatch(editor,/MutationObserver|observer\.observe/,'hero editor must never observe the global DOM');
assert.doesNotMatch(editor,/GENSRPG_VERSION\s*=/,'UI-only editor must not change global app version');
assert.match(bridge,/dungeon-grid-display-recovery-167856\.js\?v=167897/,'always-loaded bridge must restore tactical grid recovery');
assert.match(bridge,/gens-hero-editor-dynamic-167897\.js\?v=167897/,'always-loaded bridge must load safe hero editor');
assert.match(bridge,/dng_aldren\.png/,'Aldren official art must remain hard-pinned');
assert.match(sw,/gensrpg-cache-16\.78\.97-stability-guard/);
for(const critical of ['dungeon-grid-display-recovery-167856.js','dungeon-random-library-content-167832.js','dungeon-world-builder-167821.js','dng_aldren.png','gens-hero-editor-dynamic-167897.js'])assert.ok(sw.includes(critical),'critical cache entry missing: '+critical);
require('./dungeon_grid_display_recovery_v167856.test.cjs');
require('./gens_dungeon_hero_art_repair_v167874.test.cjs');
require('./dungeon_world_runtime_v167823.test.cjs');
console.log('V16.78.97 stability guard: Random/Builder grid recovery + Aldren art + safe hero editor OK');
