const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'..','assets','gensrpg','gens-dungeon-hero-art-repair-167874.js'),'utf8');
const stats=fs.readFileSync(path.join(__dirname,'..','assets','gensrpg','gens-rpg-stats-clean-167874.js'),'utf8');
assert.match(src,/GenSrpG V16\.78\.116/,'cleanup/stability bridge must carry current V16.78.116 layer');
assert.match(src,/rpgBaseHp/,'legacy HP editor card must be targeted');
assert.match(src,/rpgBaseMana/,'legacy Mana editor card must be targeted');
assert.match(src,/rpgPhysicalFormula/,'legacy characteristic modifiers card must be targeted');
assert.match(src,/closest\?\.\("\.smodCard"\)/,'cleanup must hide the old UI card, not remove engine data');
assert.match(src,/card\.hidden=true/,'obsolete editor cards must be hidden');
assert.match(src,/cleanupLegacyRpgEditor/,'cleanup must run from the existing always-loaded bridge');
assert.match(src,/renderRpgUniverseEditor/,'system editor cleanup must be tied to its explicit lifecycle');
assert.match(src,/openHeroCreator/,'hero editor cleanup must be tied to its explicit lifecycle');
assert.match(src,/applyCustomHeroesMulti/,'hero art repair must also survive CHARS rebuild');
assert.match(src,/gens-canonical-detection-1678107\.js\?v=1678108/,'canonical detection V108 must be loaded from the stable runtime bridge');
assert.match(src,/gens-dice-performance-1678108\.js\?v=1678112/,'mobile dice V112 layer must be loaded from the stable runtime bridge');
assert.match(src,/gens-combat-runtime-performance-1678110\.js\?v=1678116/,'combat runtime performance V115 layer must be lazy-loaded by the V116 bridge');
assert.match(src,/gens-combat-flow-1678111\.js\?v=1678115/,'combat flow must keep the validated V115 cache-bust');
assert.match(src,/DUNGEON_ENTRY_HOOKS/,'combat performance loading must stay scoped to Dungeon entry');
assert.match(src,/loadCombatPerformance/,'combat performance must have an explicit lazy loader');
const runtimeBridge=(src.match(/function loadRuntimeBridges\(\)\{[^\n]+/)||[''])[0];
assert.ok(!runtimeBridge.includes('COMBAT_PERF_SRC'),'global startup bridge must not load combat performance');
const hookAll=(src.match(/function hookAll\(\)\{[^\n]+/)||[''])[0];
assert.ok(!hookAll.includes('renderDungeonHeroStats')&&!hookAll.includes('renderDungeonAttributes'),'editor/visual cleanup must stay off combat-hot stat renderers');
assert.doesNotMatch(src,/MutationObserver|\.observe\s*\(/,'cleanup bridge must not observe unrelated UI panels globally');
assert.match(stats,/APP_VERSION="16\.78\.95"/,'single stats module must remain on validated V16.78.95 engine');
assert.match(stats,/DUNGEON_DEFAULT_ATTRIBUTES/,'canonical runtime link must remain intact');
assert.match(stats,/legacyEffectsMigrated94/,'legacy hidden coefficients must remain neutralized');
assert.doesNotMatch(src,/delete\s+R\.|delete\s+.*rpgBaseHp|delete\s+.*rpgBaseMana/,'visual cleanup must not delete runtime settings');
console.log('GenSrpG V16.78.116 scoped editor cleanup + lazy Dungeon combat bridge + V16.78.95 stats engine: OK');
