const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const cp=require('node:child_process');
const root=path.join(__dirname,'..');
const patcher=path.join(root,'tools','patch_generic_stat_grid_v167890.py');
const source=path.join(root,'index.html');
assert.ok(fs.existsSync(patcher));assert.ok(fs.existsSync(source));
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'gens-v167898-')),target=path.join(tmp,'index.html');
fs.copyFileSync(source,target);cp.execFileSync('python3',[patcher,target],{stdio:'pipe'});
const html=fs.readFileSync(target,'utf8');
assert.match(html,/gensCanonicalStatGridV167898/,'final build must contain the V16.78.98 canonical renderer');
assert.match(html,/GENS_STAT_ALIAS_V167897=\{agility:"agilite",spirit:"esprit"\}/,'legacy editor ids must normalize to runtime ids');
assert.match(html,/host\.innerHTML=defs\.map/,'the grid must be generated from active definitions');
assert.match(html,/state\.rpgStatSpent=Math\.max\(0,Number\(state\.rpgStatSpent\)\|\|0\)\+actual/,'spent points must stay numeric');
assert.match(html,/state\.rpgStatSpentById/,'per-stat refunds must remain separate');
assert.match(html,/gsrCustomStatDescription/);assert.match(html,/Influence : /);
assert.match(html,/dataset\.gensUnifiedStatGrid="167898"/);
assert.match(html,/GENSRPG_VERSION="16\.78\.98"/);
assert.match(html,/renderDungeonAttributes__native167890\.apply\(this,arguments\);\s*gensRenderCanonicalAttributesV167897\(\)/s,'native renderer must rebuild derived stats and rule summaries before canonical grid replacement');
assert.match(html,/dungeonHeroStats/,'compact stat strip cleanup must be present');
assert.match(html,/compact\.style\.display="none";compact\.innerHTML=""/,'legacy compact duplicate stats must be hidden');
assert.match(html,/d&&dungeonSheetTab==="skills"\?"block":"none"/,'talent tree must only be visible in the skills tab');
assert.doesNotMatch(html,/<span class="customHeroBadge">PERSONNALISÉ<\/span>/,'obsolete custom hero badge must not survive the final build');
assert.doesNotMatch(html,/badge\.textContent=h\.dungeonBuiltin\?"RPG INTÉGRÉ":"PERSONNALISÉ"/,'in-game hero cards must not show PERSONNALISÉ');
assert.match(html,/gensCurrentRpgProfileActiveV167894/,'active gameplay profile must remain authoritative');
const start=html.indexOf('/* gensCanonicalStatGridV167898'),end=html.indexOf('</script>',start);assert.ok(start>=0&&end>start);
const wrapper=html.slice(start,end);
assert.doesNotMatch(wrapper,/MutationObserver|setInterval|startDungeonCombat|enemyCells\s*=|dungeonRoom\s*=/,'stat renderer must not touch spatial/combat systems');
cp.execFileSync('python3',[patcher,target],{stdio:'pipe'});
const twice=fs.readFileSync(target,'utf8');
assert.equal((twice.match(/gensCanonicalStatGridV167898/g)||[]).length,1,'patch must be idempotent');
const site=process.argv[2]&&fs.existsSync(process.argv[2])?fs.readFileSync(process.argv[2],'utf8'):null;
if(site){
 assert.match(site,/gensCanonicalStatGridV167898/);
 assert.match(site,/GENSRPG_VERSION="16\.78\.98"/);
 assert.doesNotMatch(site,/<span class="customHeroBadge">PERSONNALISÉ<\/span>/);
}
console.log('GenSrpG stat/talent sheet cleanup V16.78.98 regression: OK');
